version: "3"

services:
  debugger:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=alpine:3.11
        - MIRRIR=mirrors.aliyun.com
        - CALICOCTL_VERSION=v3.14.0
        - TERMSHARK_VERSION=2.1.1
    container_name: debugger
    hostname: debugger
    image: icmdb/debugger:alpine-3.11

